Repository domthom21/eurocodedesign, pull requests merged in 2023-07, with the labels that each got.

#45 Add CrossSectionClassification from EN 1993-1-1
  CONTRIBUTING.rst
  eurocodedesign/geometry/steelsections/__init__.py
  eurocodedesign/geometry/steelsections/_data/rhs_en10219_en10210_2006.csv
  eurocodedesign/geometry/steelsections/_data/shs_en10219_en10210_2006.csv
  eurocodedesign/materials/structuralsteel.py
  eurocodedesign/standard/ec3/crosssectionclassification.py
  eurocodedesign/units/__init__.py
  tests/test_crosssectionclassification.py
  tests/test_steelsections.py
  tests/test_structuralsteel.py
Labels: enhancement

#53 Fix build errors
  eurocodedesign/geometry/steelsections/__init__.py
  eurocodedesign/materials/structuralsteel.py
  eurocodedesign/standard/ec3/crosssectionclassification.py
  eurocodedesign/units/__init__.py
  setup.py
  tests/test_crosssectionclassification.py
  tests/test_steelsections.py
Labels: bug

#54 Add code coverage to pytest
  requirements_dev.txt
  tox.ini
Labels: enhancement, meta

#68 Add inject_stepper decorator
  eurocodedesign/stepper/__init__.py
Labels: enhancement
